### ISSUE TITLE
how to expose admin console port

### ISSUE THREAD

**Issue by geddski** [stuartpb/rethinkdb-dockerfiles#2]
So I've installed this on a digital ocean droplet, ssh in and `docker ps` shows it's running. Now how do I access the administrative web console, know which port to use for the driver connection, etc?

**Comment by stuartpb** [comment]
See https://github.com/docker-library/docs/blob/master/rethinkdb/README.md#how-to-use-this-image

**Comment by stuartpb** [comment]
https://github.com/docker-library/docs/blob/master/rethinkdb/README.md#connecting-to-the-web-admin-interface-on-a-remote--virtual-host-via-ssh specifically details how to set up an SSH tunnel to connect to the web console for a container running on a DO droplet.

**Comment by stuartpb** [comment]
For the client driver, to go into a little more detail after https://github.com/docker-library/docs/blob/master/rethinkdb/README.md#connect-the-instance-to-an-application, within the `some-app` container, you'd want to connect to the IP and port specified in the `RDB_PORT_28015_TCP_ADDR` and `RDB_PORT_28015_TCP_PORT` environment variables, respectively.

All this is a bit of a verbose hassle (and there's still more to be done after getting it taken care of), which is why I use [Plushu](https://github.com/plushu/plushu) for managing apps and addon service connections / environments like this, and [envigor](https://github.com/stuartpb/envigor) to figure out the configuration on the app side, [like this](https://github.com/latertime/laterti.me/blob/master/server.js#L23) (followed by [endex](https://github.com/stuartpb/endex) to ensure the tables/indices are created).

**Comment by stuartpb** [comment]
Note that when I say Plushu I'm mostly referring to the [Plusku](https://meta.sh/setup/plusku) setup.

**Comment by geddski** [comment]
@stuartpb what would the `remote` variable be in the case of using boot2docker (VM) on a mac?

**Comment by geddski** [comment]
there's gotta be an easier way to enable/view the admin interface...

**Comment by stuartpb** [comment]
`remote` would be the IP for whatever network interface you're exposing the VM on. Following the directions from https://docs.docker.com/installation/mac/#from-your-command-line, that would be `boot2docker ip`.

If you don't like SSH tunneling, the simplest way to connect to it would be to either use a port exposing option like `-p 8080` and visit `$(boot2docker ip):8080`, or (if the container is already running) using an [ambassador container](https://registry.hub.docker.com/u/svendowideit/ambassador/) to expose the port. (This approach was [ommitted from the README](https://github.com/docker-library/docs/pull/137#discussion-diff-22982964) as part of the initial pull request discussion, at the request of upstream.)

**Comment by geddski** [comment]
@stuartpb thanks.
