### ISSUE TITLE
Include python driver?

### ISSUE THREAD

**Issue by nthtran** [stuartpb/rethinkdb-dockerfiles#6]
So you can exec `rethinkdb dump` or `rethinkdb index-rebuild`.

Example:
https://github.com/dockerfile/rethinkdb/commit/e9da66d3d0111a4900252541cff31f4bdb634170

**Comment by stuartpb** [comment]
If I were to do this, I'd do it as a separate image, since Python/pip/everything bring a lot of heavyweight dependencies with them (you don't see most of it there because the base image pilwon used for all the "dockerfile" images was already a massive kitchen sink).

Indeed, if you want to run the RethinkDB driver using official images, you're better off running `docker run python bash -c 'pip install rethinkdb && rethinkdb dump'`.

**Comment by stuartpb** [comment]
If you want your own RethinkDB driver image, run this:

```bash
cid=`docker run -d python:2 pip install rethinkdb`
docker logs -f "$cid"
docker commit "$cid" rdbpydri
docker rm "$cid"
```

Usage:

```bash
docker run rdbpydri rethinkdb dump
docker run rdbpydri rethinkdb index-rebuild
# etc.
```

**Comment by nthtran** [comment]
Fair enough I'll just do this then. Thanks!

**Comment by aleclarson** [comment]
Here's another option found by @jordanh:

`rethinkdb-backup.sh`:
```sh
#!/bin/bash
# see: https://github.com/petecoop/rethinkdb-driver
now=$(date +"%Y_%m_%d_%H_%M_%S")
docker run --rm \
  --link dokku.rethinkdb.rethinkdb:rethinkdb \
  -v $(readlink -e $1):/backup \
  petecoop/rethinkdb-driver rethinkdb-dump -c rethinkdb -f /backup/rethinkdb_backup_$now.tar.gz
```

and `rethinkdb-restore.sh`:
```sh
#!/bin/bash
# see: https://github.com/petecoop/rethinkdb-driver
docker run --rm \
  --link dokku.rethinkdb.rethinkdb:rethinkdb \
  -v $(dirname $(readlink -e $1)):/backup \
  petecoop/rethinkdb-driver rethinkdb-restore -c rethinkdb --force /backup/$(basename $(readlink -e $1))
```
